/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) masses_chain_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {24, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};
static const casadi_int casadi_s4[111] = 
  {24, 24, 0, 6, 12, 18, 19, 20,
  21, 30, 39, 48, 49, 50, 51, 57,
  63, 69, 70, 71, 72, 75, 78, 81,
  82, 83, 84, 3, 4, 5, 9, 10,
  11, 3, 4, 5, 9, 10, 11, 3,
  4, 5, 9, 10, 11, 0, 1, 2,
  3, 4, 5, 9, 10, 11, 15, 16,
  17, 3, 4, 5, 9, 10, 11, 15,
  16, 17, 3, 4, 5, 9, 10, 11,
  15, 16, 17, 6, 7, 8, 9, 10,
  11, 15, 16, 17, 9, 10, 11, 15,
  16, 17, 9, 10, 11, 15, 16, 17,
  12, 13, 14, 15, 16, 17, 15, 16,
  17, 15, 16, 17, 18, 19, 20};
static const casadi_int casadi_s5[51] = 
  {24, 24, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 20,
  21, 22, 23};
static const casadi_int casadi_s6[9] = 
  {24, 3, 0, 1, 2, 3, 21, 22,
  23};
static const casadi_int casadi_s7[3] = {24, 0, 1};

/* masses_chain_impl_dae_jac_x_xdot_u_z:(i0[24],i1[24],i2[3],i3[],i4)->(o0[24x24,84nz],o1[24x24,24nz],o2[24x3,3nz],o3[24x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29;
  a00=3.3333333333333336e+01;
  a01=arg[0]? arg[0][6] : 0;
  a02=arg[0]? arg[0][0] : 0;
  a03=(a01-a02);
  a04=3.3000000000000002e-02;
  a05=casadi_sq(a03);
  a06=arg[0]? arg[0][7] : 0;
  a07=arg[0]? arg[0][1] : 0;
  a08=(a06-a07);
  a09=casadi_sq(a08);
  a05=(a05+a09);
  a09=arg[0]? arg[0][8] : 0;
  a10=arg[0]? arg[0][2] : 0;
  a11=(a09-a10);
  a12=casadi_sq(a11);
  a05=(a05+a12);
  a05=sqrt(a05);
  a12=(a04/a05);
  a13=(a12/a05);
  a14=(a03/a05);
  a14=(a13*a14);
  a15=(a03*a14);
  a16=1.;
  a12=(a16-a12);
  a15=(a15+a12);
  a17=casadi_sq(a02);
  a18=casadi_sq(a07);
  a17=(a17+a18);
  a18=casadi_sq(a10);
  a17=(a17+a18);
  a17=sqrt(a17);
  a18=(a04/a17);
  a19=(a18/a17);
  a20=(a02/a17);
  a20=(a19*a20);
  a21=(a02*a20);
  a18=(a16-a18);
  a21=(a21+a18);
  a21=(a15+a21);
  a21=(a00*a21);
  a21=(-a21);
  if (res[0]!=0) res[0][0]=a21;
  a21=(a08*a14);
  a22=(a07*a20);
  a22=(a21+a22);
  a22=(a00*a22);
  a22=(-a22);
  if (res[0]!=0) res[0][1]=a22;
  a14=(a11*a14);
  a20=(a10*a20);
  a20=(a14+a20);
  a20=(a00*a20);
  a20=(-a20);
  if (res[0]!=0) res[0][2]=a20;
  a20=(a00*a15);
  if (res[0]!=0) res[0][3]=a20;
  a22=(a00*a21);
  if (res[0]!=0) res[0][4]=a22;
  a23=(a00*a14);
  if (res[0]!=0) res[0][5]=a23;
  a24=(a08/a05);
  a24=(a13*a24);
  a25=(a03*a24);
  a26=(a07/a17);
  a26=(a19*a26);
  a27=(a02*a26);
  a27=(a25+a27);
  a27=(a00*a27);
  a27=(-a27);
  if (res[0]!=0) res[0][6]=a27;
  a27=(a08*a24);
  a27=(a27+a12);
  a28=(a07*a26);
  a28=(a28+a18);
  a28=(a27+a28);
  a28=(a00*a28);
  a28=(-a28);
  if (res[0]!=0) res[0][7]=a28;
  a24=(a11*a24);
  a26=(a10*a26);
  a26=(a24+a26);
  a26=(a00*a26);
  a26=(-a26);
  if (res[0]!=0) res[0][8]=a26;
  a26=(a00*a25);
  if (res[0]!=0) res[0][9]=a26;
  a28=(a00*a27);
  if (res[0]!=0) res[0][10]=a28;
  a29=(a00*a24);
  if (res[0]!=0) res[0][11]=a29;
  a05=(a11/a05);
  a13=(a13*a05);
  a03=(a03*a13);
  a17=(a10/a17);
  a19=(a19*a17);
  a02=(a02*a19);
  a02=(a03+a02);
  a02=(a00*a02);
  a02=(-a02);
  if (res[0]!=0) res[0][12]=a02;
  a08=(a08*a13);
  a07=(a07*a19);
  a07=(a08+a07);
  a07=(a00*a07);
  a07=(-a07);
  if (res[0]!=0) res[0][13]=a07;
  a11=(a11*a13);
  a11=(a11+a12);
  a10=(a10*a19);
  a10=(a10+a18);
  a10=(a11+a10);
  a10=(a00*a10);
  a10=(-a10);
  if (res[0]!=0) res[0][14]=a10;
  a10=(a00*a03);
  if (res[0]!=0) res[0][15]=a10;
  a18=(a00*a08);
  if (res[0]!=0) res[0][16]=a18;
  a19=(a00*a11);
  if (res[0]!=0) res[0][17]=a19;
  if (res[0]!=0) res[0][18]=a16;
  if (res[0]!=0) res[0][19]=a16;
  if (res[0]!=0) res[0][20]=a16;
  if (res[0]!=0) res[0][21]=a20;
  if (res[0]!=0) res[0][22]=a22;
  if (res[0]!=0) res[0][23]=a23;
  a23=arg[0]? arg[0][12] : 0;
  a01=(a23-a01);
  a22=casadi_sq(a01);
  a20=arg[0]? arg[0][13] : 0;
  a06=(a20-a06);
  a12=casadi_sq(a06);
  a22=(a22+a12);
  a12=arg[0]? arg[0][14] : 0;
  a09=(a12-a09);
  a13=casadi_sq(a09);
  a22=(a22+a13);
  a22=sqrt(a22);
  a13=(a04/a22);
  a07=(a13/a22);
  a02=(a01/a22);
  a02=(a07*a02);
  a17=(a01*a02);
  a13=(a16-a13);
  a17=(a17+a13);
  a15=(a17+a15);
  a15=(a00*a15);
  a15=(-a15);
  if (res[0]!=0) res[0][24]=a15;
  a15=(a06*a02);
  a21=(a15+a21);
  a21=(a00*a21);
  a21=(-a21);
  if (res[0]!=0) res[0][25]=a21;
  a02=(a09*a02);
  a14=(a02+a14);
  a14=(a00*a14);
  a14=(-a14);
  if (res[0]!=0) res[0][26]=a14;
  a14=(a00*a17);
  if (res[0]!=0) res[0][27]=a14;
  a21=(a00*a15);
  if (res[0]!=0) res[0][28]=a21;
  a05=(a00*a02);
  if (res[0]!=0) res[0][29]=a05;
  if (res[0]!=0) res[0][30]=a26;
  if (res[0]!=0) res[0][31]=a28;
  if (res[0]!=0) res[0][32]=a29;
  a29=(a06/a22);
  a29=(a07*a29);
  a28=(a01*a29);
  a25=(a28+a25);
  a25=(a00*a25);
  a25=(-a25);
  if (res[0]!=0) res[0][33]=a25;
  a25=(a06*a29);
  a25=(a25+a13);
  a27=(a25+a27);
  a27=(a00*a27);
  a27=(-a27);
  if (res[0]!=0) res[0][34]=a27;
  a29=(a09*a29);
  a24=(a29+a24);
  a24=(a00*a24);
  a24=(-a24);
  if (res[0]!=0) res[0][35]=a24;
  a24=(a00*a28);
  if (res[0]!=0) res[0][36]=a24;
  a27=(a00*a25);
  if (res[0]!=0) res[0][37]=a27;
  a26=(a00*a29);
  if (res[0]!=0) res[0][38]=a26;
  if (res[0]!=0) res[0][39]=a10;
  if (res[0]!=0) res[0][40]=a18;
  if (res[0]!=0) res[0][41]=a19;
  a22=(a09/a22);
  a07=(a07*a22);
  a01=(a01*a07);
  a03=(a01+a03);
  a03=(a00*a03);
  a03=(-a03);
  if (res[0]!=0) res[0][42]=a03;
  a06=(a06*a07);
  a08=(a06+a08);
  a08=(a00*a08);
  a08=(-a08);
  if (res[0]!=0) res[0][43]=a08;
  a09=(a09*a07);
  a09=(a09+a13);
  a11=(a09+a11);
  a11=(a00*a11);
  a11=(-a11);
  if (res[0]!=0) res[0][44]=a11;
  a11=(a00*a01);
  if (res[0]!=0) res[0][45]=a11;
  a13=(a00*a06);
  if (res[0]!=0) res[0][46]=a13;
  a07=(a00*a09);
  if (res[0]!=0) res[0][47]=a07;
  if (res[0]!=0) res[0][48]=a16;
  if (res[0]!=0) res[0][49]=a16;
  if (res[0]!=0) res[0][50]=a16;
  if (res[0]!=0) res[0][51]=a14;
  if (res[0]!=0) res[0][52]=a21;
  if (res[0]!=0) res[0][53]=a05;
  a05=arg[0]? arg[0][18] : 0;
  a05=(a05-a23);
  a23=casadi_sq(a05);
  a21=arg[0]? arg[0][19] : 0;
  a21=(a21-a20);
  a20=casadi_sq(a21);
  a23=(a23+a20);
  a20=arg[0]? arg[0][20] : 0;
  a20=(a20-a12);
  a12=casadi_sq(a20);
  a23=(a23+a12);
  a23=sqrt(a23);
  a04=(a04/a23);
  a12=(a04/a23);
  a14=(a05/a23);
  a14=(a12*a14);
  a08=(a05*a14);
  a04=(a16-a04);
  a08=(a08+a04);
  a17=(a08+a17);
  a17=(a00*a17);
  a17=(-a17);
  if (res[0]!=0) res[0][54]=a17;
  a17=(a21*a14);
  a15=(a17+a15);
  a15=(a00*a15);
  a15=(-a15);
  if (res[0]!=0) res[0][55]=a15;
  a14=(a20*a14);
  a02=(a14+a02);
  a02=(a00*a02);
  a02=(-a02);
  if (res[0]!=0) res[0][56]=a02;
  if (res[0]!=0) res[0][57]=a24;
  if (res[0]!=0) res[0][58]=a27;
  if (res[0]!=0) res[0][59]=a26;
  a26=(a21/a23);
  a26=(a12*a26);
  a27=(a05*a26);
  a28=(a27+a28);
  a28=(a00*a28);
  a28=(-a28);
  if (res[0]!=0) res[0][60]=a28;
  a28=(a21*a26);
  a28=(a28+a04);
  a25=(a28+a25);
  a25=(a00*a25);
  a25=(-a25);
  if (res[0]!=0) res[0][61]=a25;
  a26=(a20*a26);
  a29=(a26+a29);
  a29=(a00*a29);
  a29=(-a29);
  if (res[0]!=0) res[0][62]=a29;
  if (res[0]!=0) res[0][63]=a11;
  if (res[0]!=0) res[0][64]=a13;
  if (res[0]!=0) res[0][65]=a07;
  a23=(a20/a23);
  a12=(a12*a23);
  a05=(a05*a12);
  a01=(a05+a01);
  a01=(a00*a01);
  a01=(-a01);
  if (res[0]!=0) res[0][66]=a01;
  a21=(a21*a12);
  a06=(a21+a06);
  a06=(a00*a06);
  a06=(-a06);
  if (res[0]!=0) res[0][67]=a06;
  a20=(a20*a12);
  a20=(a20+a04);
  a09=(a20+a09);
  a09=(a00*a09);
  a09=(-a09);
  if (res[0]!=0) res[0][68]=a09;
  if (res[0]!=0) res[0][69]=a16;
  if (res[0]!=0) res[0][70]=a16;
  if (res[0]!=0) res[0][71]=a16;
  a08=(a00*a08);
  if (res[0]!=0) res[0][72]=a08;
  a17=(a00*a17);
  if (res[0]!=0) res[0][73]=a17;
  a14=(a00*a14);
  if (res[0]!=0) res[0][74]=a14;
  a27=(a00*a27);
  if (res[0]!=0) res[0][75]=a27;
  a28=(a00*a28);
  if (res[0]!=0) res[0][76]=a28;
  a26=(a00*a26);
  if (res[0]!=0) res[0][77]=a26;
  a05=(a00*a05);
  if (res[0]!=0) res[0][78]=a05;
  a21=(a00*a21);
  if (res[0]!=0) res[0][79]=a21;
  a00=(a00*a20);
  if (res[0]!=0) res[0][80]=a00;
  if (res[0]!=0) res[0][81]=a16;
  if (res[0]!=0) res[0][82]=a16;
  if (res[0]!=0) res[0][83]=a16;
  a00=-1.;
  if (res[1]!=0) res[1][0]=a00;
  if (res[1]!=0) res[1][1]=a00;
  if (res[1]!=0) res[1][2]=a00;
  if (res[1]!=0) res[1][3]=a00;
  if (res[1]!=0) res[1][4]=a00;
  if (res[1]!=0) res[1][5]=a00;
  if (res[1]!=0) res[1][6]=a00;
  if (res[1]!=0) res[1][7]=a00;
  if (res[1]!=0) res[1][8]=a00;
  if (res[1]!=0) res[1][9]=a00;
  if (res[1]!=0) res[1][10]=a00;
  if (res[1]!=0) res[1][11]=a00;
  if (res[1]!=0) res[1][12]=a00;
  if (res[1]!=0) res[1][13]=a00;
  if (res[1]!=0) res[1][14]=a00;
  if (res[1]!=0) res[1][15]=a00;
  if (res[1]!=0) res[1][16]=a00;
  if (res[1]!=0) res[1][17]=a00;
  if (res[1]!=0) res[1][18]=a00;
  if (res[1]!=0) res[1][19]=a00;
  if (res[1]!=0) res[1][20]=a00;
  if (res[1]!=0) res[1][21]=a00;
  if (res[1]!=0) res[1][22]=a00;
  if (res[1]!=0) res[1][23]=a00;
  if (res[2]!=0) res[2][0]=a16;
  if (res[2]!=0) res[2][1]=a16;
  if (res[2]!=0) res[2][2]=a16;
  return 0;
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void masses_chain_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void masses_chain_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void masses_chain_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void masses_chain_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int masses_chain_impl_dae_jac_x_xdot_u_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int masses_chain_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real masses_chain_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* masses_chain_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* masses_chain_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* masses_chain_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* masses_chain_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
