/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) masses_chain_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {24, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

/* masses_chain_impl_dae_fun:(i0[24],i1[24],i2[3],i3[],i4)->(o0[24]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14;
  a00=arg[0]? arg[0][3] : 0;
  a01=arg[1]? arg[1][0] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][4] : 0;
  a01=arg[1]? arg[1][1] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][5] : 0;
  a01=arg[1]? arg[1][2] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][2]=a00;
  a00=3.3333333333333336e+01;
  a01=1.;
  a02=3.3000000000000002e-02;
  a03=arg[0]? arg[0][6] : 0;
  a04=arg[0]? arg[0][0] : 0;
  a05=(a03-a04);
  a06=casadi_sq(a05);
  a07=arg[0]? arg[0][7] : 0;
  a08=arg[0]? arg[0][1] : 0;
  a09=(a07-a08);
  a10=casadi_sq(a09);
  a06=(a06+a10);
  a10=arg[0]? arg[0][8] : 0;
  a11=arg[0]? arg[0][2] : 0;
  a12=(a10-a11);
  a13=casadi_sq(a12);
  a06=(a06+a13);
  a06=sqrt(a06);
  a06=(a02/a06);
  a06=(a01-a06);
  a05=(a06*a05);
  a13=casadi_sq(a04);
  a14=casadi_sq(a08);
  a13=(a13+a14);
  a14=casadi_sq(a11);
  a13=(a13+a14);
  a13=sqrt(a13);
  a13=(a02/a13);
  a13=(a01-a13);
  a04=(a13*a04);
  a04=(a05-a04);
  a04=(a00*a04);
  a14=arg[1]? arg[1][3] : 0;
  a04=(a04-a14);
  if (res[0]!=0) res[0][3]=a04;
  a09=(a06*a09);
  a08=(a13*a08);
  a08=(a09-a08);
  a08=(a00*a08);
  a04=arg[1]? arg[1][4] : 0;
  a08=(a08-a04);
  if (res[0]!=0) res[0][4]=a08;
  a06=(a06*a12);
  a13=(a13*a11);
  a13=(a06-a13);
  a13=(a00*a13);
  a11=9.8100000000000005e+00;
  a13=(a13-a11);
  a12=arg[1]? arg[1][5] : 0;
  a13=(a13-a12);
  if (res[0]!=0) res[0][5]=a13;
  a13=arg[0]? arg[0][9] : 0;
  a12=arg[1]? arg[1][6] : 0;
  a13=(a13-a12);
  if (res[0]!=0) res[0][6]=a13;
  a13=arg[0]? arg[0][10] : 0;
  a12=arg[1]? arg[1][7] : 0;
  a13=(a13-a12);
  if (res[0]!=0) res[0][7]=a13;
  a13=arg[0]? arg[0][11] : 0;
  a12=arg[1]? arg[1][8] : 0;
  a13=(a13-a12);
  if (res[0]!=0) res[0][8]=a13;
  a13=arg[0]? arg[0][12] : 0;
  a03=(a13-a03);
  a12=casadi_sq(a03);
  a08=arg[0]? arg[0][13] : 0;
  a07=(a08-a07);
  a04=casadi_sq(a07);
  a12=(a12+a04);
  a04=arg[0]? arg[0][14] : 0;
  a10=(a04-a10);
  a14=casadi_sq(a10);
  a12=(a12+a14);
  a12=sqrt(a12);
  a12=(a02/a12);
  a12=(a01-a12);
  a03=(a12*a03);
  a05=(a03-a05);
  a05=(a00*a05);
  a14=arg[1]? arg[1][9] : 0;
  a05=(a05-a14);
  if (res[0]!=0) res[0][9]=a05;
  a07=(a12*a07);
  a09=(a07-a09);
  a09=(a00*a09);
  a05=arg[1]? arg[1][10] : 0;
  a09=(a09-a05);
  if (res[0]!=0) res[0][10]=a09;
  a12=(a12*a10);
  a06=(a12-a06);
  a06=(a00*a06);
  a06=(a06-a11);
  a10=arg[1]? arg[1][11] : 0;
  a06=(a06-a10);
  if (res[0]!=0) res[0][11]=a06;
  a06=arg[0]? arg[0][15] : 0;
  a10=arg[1]? arg[1][12] : 0;
  a06=(a06-a10);
  if (res[0]!=0) res[0][12]=a06;
  a06=arg[0]? arg[0][16] : 0;
  a10=arg[1]? arg[1][13] : 0;
  a06=(a06-a10);
  if (res[0]!=0) res[0][13]=a06;
  a06=arg[0]? arg[0][17] : 0;
  a10=arg[1]? arg[1][14] : 0;
  a06=(a06-a10);
  if (res[0]!=0) res[0][14]=a06;
  a06=arg[0]? arg[0][18] : 0;
  a06=(a06-a13);
  a13=casadi_sq(a06);
  a10=arg[0]? arg[0][19] : 0;
  a10=(a10-a08);
  a08=casadi_sq(a10);
  a13=(a13+a08);
  a08=arg[0]? arg[0][20] : 0;
  a08=(a08-a04);
  a04=casadi_sq(a08);
  a13=(a13+a04);
  a13=sqrt(a13);
  a02=(a02/a13);
  a01=(a01-a02);
  a06=(a01*a06);
  a06=(a06-a03);
  a06=(a00*a06);
  a03=arg[1]? arg[1][15] : 0;
  a06=(a06-a03);
  if (res[0]!=0) res[0][15]=a06;
  a10=(a01*a10);
  a10=(a10-a07);
  a10=(a00*a10);
  a07=arg[1]? arg[1][16] : 0;
  a10=(a10-a07);
  if (res[0]!=0) res[0][16]=a10;
  a01=(a01*a08);
  a01=(a01-a12);
  a00=(a00*a01);
  a00=(a00-a11);
  a11=arg[1]? arg[1][17] : 0;
  a00=(a00-a11);
  if (res[0]!=0) res[0][17]=a00;
  a00=arg[0]? arg[0][21] : 0;
  a11=arg[1]? arg[1][18] : 0;
  a00=(a00-a11);
  if (res[0]!=0) res[0][18]=a00;
  a00=arg[0]? arg[0][22] : 0;
  a11=arg[1]? arg[1][19] : 0;
  a00=(a00-a11);
  if (res[0]!=0) res[0][19]=a00;
  a00=arg[0]? arg[0][23] : 0;
  a11=arg[1]? arg[1][20] : 0;
  a00=(a00-a11);
  if (res[0]!=0) res[0][20]=a00;
  a00=arg[2]? arg[2][0] : 0;
  a11=arg[1]? arg[1][21] : 0;
  a00=(a00-a11);
  if (res[0]!=0) res[0][21]=a00;
  a00=arg[2]? arg[2][1] : 0;
  a11=arg[1]? arg[1][22] : 0;
  a00=(a00-a11);
  if (res[0]!=0) res[0][22]=a00;
  a00=arg[2]? arg[2][2] : 0;
  a11=arg[1]? arg[1][23] : 0;
  a00=(a00-a11);
  if (res[0]!=0) res[0][23]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void masses_chain_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void masses_chain_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void masses_chain_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void masses_chain_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int masses_chain_impl_dae_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int masses_chain_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real masses_chain_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* masses_chain_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* masses_chain_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* masses_chain_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* masses_chain_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
