/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) masses_chain_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {24, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};
static const casadi_int casadi_s4[111] = 
  {24, 24, 0, 6, 12, 18, 19, 20,
  21, 30, 39, 48, 49, 50, 51, 57,
  63, 69, 70, 71, 72, 75, 78, 81,
  82, 83, 84, 3, 4, 5, 9, 10,
  11, 3, 4, 5, 9, 10, 11, 3,
  4, 5, 9, 10, 11, 0, 1, 2,
  3, 4, 5, 9, 10, 11, 15, 16,
  17, 3, 4, 5, 9, 10, 11, 15,
  16, 17, 3, 4, 5, 9, 10, 11,
  15, 16, 17, 6, 7, 8, 9, 10,
  11, 15, 16, 17, 9, 10, 11, 15,
  16, 17, 9, 10, 11, 15, 16, 17,
  12, 13, 14, 15, 16, 17, 15, 16,
  17, 15, 16, 17, 18, 19, 20};
static const casadi_int casadi_s5[51] = 
  {24, 24, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 20,
  21, 22, 23};
static const casadi_int casadi_s6[9] = 
  {24, 3, 0, 1, 2, 3, 21, 22,
  23};

/* masses_chain_impl_dae_fun_jac_x_xdot_u:(i0[24],i1[24],i2[3],i3[],i4)->(o0[24],o1[24x24,84nz],o2[24x24,24nz],o3[24x3,3nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37;
  a00=arg[0]? arg[0][3] : 0;
  a01=arg[1]? arg[1][0] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][4] : 0;
  a01=arg[1]? arg[1][1] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][5] : 0;
  a01=arg[1]? arg[1][2] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][2]=a00;
  a00=3.3333333333333336e+01;
  a01=1.;
  a02=3.3000000000000002e-02;
  a03=arg[0]? arg[0][6] : 0;
  a04=arg[0]? arg[0][0] : 0;
  a05=(a03-a04);
  a06=casadi_sq(a05);
  a07=arg[0]? arg[0][7] : 0;
  a08=arg[0]? arg[0][1] : 0;
  a09=(a07-a08);
  a10=casadi_sq(a09);
  a06=(a06+a10);
  a10=arg[0]? arg[0][8] : 0;
  a11=arg[0]? arg[0][2] : 0;
  a12=(a10-a11);
  a13=casadi_sq(a12);
  a06=(a06+a13);
  a06=sqrt(a06);
  a13=(a02/a06);
  a14=(a01-a13);
  a15=(a14*a05);
  a16=casadi_sq(a04);
  a17=casadi_sq(a08);
  a16=(a16+a17);
  a17=casadi_sq(a11);
  a16=(a16+a17);
  a16=sqrt(a16);
  a17=(a02/a16);
  a18=(a01-a17);
  a19=(a18*a04);
  a19=(a15-a19);
  a19=(a00*a19);
  a20=arg[1]? arg[1][3] : 0;
  a19=(a19-a20);
  if (res[0]!=0) res[0][3]=a19;
  a19=(a14*a09);
  a20=(a18*a08);
  a20=(a19-a20);
  a20=(a00*a20);
  a21=arg[1]? arg[1][4] : 0;
  a20=(a20-a21);
  if (res[0]!=0) res[0][4]=a20;
  a20=(a14*a12);
  a21=(a18*a11);
  a21=(a20-a21);
  a21=(a00*a21);
  a22=9.8100000000000005e+00;
  a21=(a21-a22);
  a23=arg[1]? arg[1][5] : 0;
  a21=(a21-a23);
  if (res[0]!=0) res[0][5]=a21;
  a21=arg[0]? arg[0][9] : 0;
  a23=arg[1]? arg[1][6] : 0;
  a21=(a21-a23);
  if (res[0]!=0) res[0][6]=a21;
  a21=arg[0]? arg[0][10] : 0;
  a23=arg[1]? arg[1][7] : 0;
  a21=(a21-a23);
  if (res[0]!=0) res[0][7]=a21;
  a21=arg[0]? arg[0][11] : 0;
  a23=arg[1]? arg[1][8] : 0;
  a21=(a21-a23);
  if (res[0]!=0) res[0][8]=a21;
  a21=arg[0]? arg[0][12] : 0;
  a03=(a21-a03);
  a23=casadi_sq(a03);
  a24=arg[0]? arg[0][13] : 0;
  a07=(a24-a07);
  a25=casadi_sq(a07);
  a23=(a23+a25);
  a25=arg[0]? arg[0][14] : 0;
  a10=(a25-a10);
  a26=casadi_sq(a10);
  a23=(a23+a26);
  a23=sqrt(a23);
  a26=(a02/a23);
  a27=(a01-a26);
  a28=(a27*a03);
  a15=(a28-a15);
  a15=(a00*a15);
  a29=arg[1]? arg[1][9] : 0;
  a15=(a15-a29);
  if (res[0]!=0) res[0][9]=a15;
  a15=(a27*a07);
  a19=(a15-a19);
  a19=(a00*a19);
  a29=arg[1]? arg[1][10] : 0;
  a19=(a19-a29);
  if (res[0]!=0) res[0][10]=a19;
  a19=(a27*a10);
  a20=(a19-a20);
  a20=(a00*a20);
  a20=(a20-a22);
  a29=arg[1]? arg[1][11] : 0;
  a20=(a20-a29);
  if (res[0]!=0) res[0][11]=a20;
  a20=arg[0]? arg[0][15] : 0;
  a29=arg[1]? arg[1][12] : 0;
  a20=(a20-a29);
  if (res[0]!=0) res[0][12]=a20;
  a20=arg[0]? arg[0][16] : 0;
  a29=arg[1]? arg[1][13] : 0;
  a20=(a20-a29);
  if (res[0]!=0) res[0][13]=a20;
  a20=arg[0]? arg[0][17] : 0;
  a29=arg[1]? arg[1][14] : 0;
  a20=(a20-a29);
  if (res[0]!=0) res[0][14]=a20;
  a20=arg[0]? arg[0][18] : 0;
  a20=(a20-a21);
  a21=casadi_sq(a20);
  a29=arg[0]? arg[0][19] : 0;
  a29=(a29-a24);
  a24=casadi_sq(a29);
  a21=(a21+a24);
  a24=arg[0]? arg[0][20] : 0;
  a24=(a24-a25);
  a25=casadi_sq(a24);
  a21=(a21+a25);
  a21=sqrt(a21);
  a02=(a02/a21);
  a25=(a01-a02);
  a30=(a25*a20);
  a30=(a30-a28);
  a30=(a00*a30);
  a28=arg[1]? arg[1][15] : 0;
  a30=(a30-a28);
  if (res[0]!=0) res[0][15]=a30;
  a30=(a25*a29);
  a30=(a30-a15);
  a30=(a00*a30);
  a15=arg[1]? arg[1][16] : 0;
  a30=(a30-a15);
  if (res[0]!=0) res[0][16]=a30;
  a30=(a25*a24);
  a30=(a30-a19);
  a30=(a00*a30);
  a30=(a30-a22);
  a22=arg[1]? arg[1][17] : 0;
  a30=(a30-a22);
  if (res[0]!=0) res[0][17]=a30;
  a30=arg[0]? arg[0][21] : 0;
  a22=arg[1]? arg[1][18] : 0;
  a30=(a30-a22);
  if (res[0]!=0) res[0][18]=a30;
  a30=arg[0]? arg[0][22] : 0;
  a22=arg[1]? arg[1][19] : 0;
  a30=(a30-a22);
  if (res[0]!=0) res[0][19]=a30;
  a30=arg[0]? arg[0][23] : 0;
  a22=arg[1]? arg[1][20] : 0;
  a30=(a30-a22);
  if (res[0]!=0) res[0][20]=a30;
  a30=arg[2]? arg[2][0] : 0;
  a22=arg[1]? arg[1][21] : 0;
  a30=(a30-a22);
  if (res[0]!=0) res[0][21]=a30;
  a30=arg[2]? arg[2][1] : 0;
  a22=arg[1]? arg[1][22] : 0;
  a30=(a30-a22);
  if (res[0]!=0) res[0][22]=a30;
  a30=arg[2]? arg[2][2] : 0;
  a22=arg[1]? arg[1][23] : 0;
  a30=(a30-a22);
  if (res[0]!=0) res[0][23]=a30;
  a13=(a13/a06);
  a30=(a05/a06);
  a30=(a13*a30);
  a22=(a05*a30);
  a22=(a22+a14);
  a17=(a17/a16);
  a19=(a04/a16);
  a19=(a17*a19);
  a15=(a04*a19);
  a15=(a15+a18);
  a15=(a22+a15);
  a15=(a00*a15);
  a15=(-a15);
  if (res[1]!=0) res[1][0]=a15;
  a15=(a09*a30);
  a28=(a08*a19);
  a28=(a15+a28);
  a28=(a00*a28);
  a28=(-a28);
  if (res[1]!=0) res[1][1]=a28;
  a30=(a12*a30);
  a19=(a11*a19);
  a19=(a30+a19);
  a19=(a00*a19);
  a19=(-a19);
  if (res[1]!=0) res[1][2]=a19;
  a19=(a00*a22);
  if (res[1]!=0) res[1][3]=a19;
  a28=(a00*a15);
  if (res[1]!=0) res[1][4]=a28;
  a31=(a00*a30);
  if (res[1]!=0) res[1][5]=a31;
  a32=(a09/a06);
  a32=(a13*a32);
  a33=(a05*a32);
  a34=(a08/a16);
  a34=(a17*a34);
  a35=(a04*a34);
  a35=(a33+a35);
  a35=(a00*a35);
  a35=(-a35);
  if (res[1]!=0) res[1][6]=a35;
  a35=(a09*a32);
  a35=(a35+a14);
  a36=(a08*a34);
  a36=(a36+a18);
  a36=(a35+a36);
  a36=(a00*a36);
  a36=(-a36);
  if (res[1]!=0) res[1][7]=a36;
  a32=(a12*a32);
  a34=(a11*a34);
  a34=(a32+a34);
  a34=(a00*a34);
  a34=(-a34);
  if (res[1]!=0) res[1][8]=a34;
  a34=(a00*a33);
  if (res[1]!=0) res[1][9]=a34;
  a36=(a00*a35);
  if (res[1]!=0) res[1][10]=a36;
  a37=(a00*a32);
  if (res[1]!=0) res[1][11]=a37;
  a06=(a12/a06);
  a13=(a13*a06);
  a05=(a05*a13);
  a16=(a11/a16);
  a17=(a17*a16);
  a04=(a04*a17);
  a04=(a05+a04);
  a04=(a00*a04);
  a04=(-a04);
  if (res[1]!=0) res[1][12]=a04;
  a09=(a09*a13);
  a08=(a08*a17);
  a08=(a09+a08);
  a08=(a00*a08);
  a08=(-a08);
  if (res[1]!=0) res[1][13]=a08;
  a12=(a12*a13);
  a12=(a12+a14);
  a11=(a11*a17);
  a11=(a11+a18);
  a11=(a12+a11);
  a11=(a00*a11);
  a11=(-a11);
  if (res[1]!=0) res[1][14]=a11;
  a11=(a00*a05);
  if (res[1]!=0) res[1][15]=a11;
  a18=(a00*a09);
  if (res[1]!=0) res[1][16]=a18;
  a17=(a00*a12);
  if (res[1]!=0) res[1][17]=a17;
  if (res[1]!=0) res[1][18]=a01;
  if (res[1]!=0) res[1][19]=a01;
  if (res[1]!=0) res[1][20]=a01;
  if (res[1]!=0) res[1][21]=a19;
  if (res[1]!=0) res[1][22]=a28;
  if (res[1]!=0) res[1][23]=a31;
  a26=(a26/a23);
  a31=(a03/a23);
  a31=(a26*a31);
  a28=(a03*a31);
  a28=(a28+a27);
  a22=(a28+a22);
  a22=(a00*a22);
  a22=(-a22);
  if (res[1]!=0) res[1][24]=a22;
  a22=(a07*a31);
  a15=(a22+a15);
  a15=(a00*a15);
  a15=(-a15);
  if (res[1]!=0) res[1][25]=a15;
  a31=(a10*a31);
  a30=(a31+a30);
  a30=(a00*a30);
  a30=(-a30);
  if (res[1]!=0) res[1][26]=a30;
  a30=(a00*a28);
  if (res[1]!=0) res[1][27]=a30;
  a15=(a00*a22);
  if (res[1]!=0) res[1][28]=a15;
  a19=(a00*a31);
  if (res[1]!=0) res[1][29]=a19;
  if (res[1]!=0) res[1][30]=a34;
  if (res[1]!=0) res[1][31]=a36;
  if (res[1]!=0) res[1][32]=a37;
  a37=(a07/a23);
  a37=(a26*a37);
  a36=(a03*a37);
  a33=(a36+a33);
  a33=(a00*a33);
  a33=(-a33);
  if (res[1]!=0) res[1][33]=a33;
  a33=(a07*a37);
  a33=(a33+a27);
  a35=(a33+a35);
  a35=(a00*a35);
  a35=(-a35);
  if (res[1]!=0) res[1][34]=a35;
  a37=(a10*a37);
  a32=(a37+a32);
  a32=(a00*a32);
  a32=(-a32);
  if (res[1]!=0) res[1][35]=a32;
  a32=(a00*a36);
  if (res[1]!=0) res[1][36]=a32;
  a35=(a00*a33);
  if (res[1]!=0) res[1][37]=a35;
  a34=(a00*a37);
  if (res[1]!=0) res[1][38]=a34;
  if (res[1]!=0) res[1][39]=a11;
  if (res[1]!=0) res[1][40]=a18;
  if (res[1]!=0) res[1][41]=a17;
  a23=(a10/a23);
  a26=(a26*a23);
  a03=(a03*a26);
  a05=(a03+a05);
  a05=(a00*a05);
  a05=(-a05);
  if (res[1]!=0) res[1][42]=a05;
  a07=(a07*a26);
  a09=(a07+a09);
  a09=(a00*a09);
  a09=(-a09);
  if (res[1]!=0) res[1][43]=a09;
  a10=(a10*a26);
  a10=(a10+a27);
  a12=(a10+a12);
  a12=(a00*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][44]=a12;
  a12=(a00*a03);
  if (res[1]!=0) res[1][45]=a12;
  a27=(a00*a07);
  if (res[1]!=0) res[1][46]=a27;
  a26=(a00*a10);
  if (res[1]!=0) res[1][47]=a26;
  if (res[1]!=0) res[1][48]=a01;
  if (res[1]!=0) res[1][49]=a01;
  if (res[1]!=0) res[1][50]=a01;
  if (res[1]!=0) res[1][51]=a30;
  if (res[1]!=0) res[1][52]=a15;
  if (res[1]!=0) res[1][53]=a19;
  a02=(a02/a21);
  a19=(a20/a21);
  a19=(a02*a19);
  a15=(a20*a19);
  a15=(a15+a25);
  a28=(a15+a28);
  a28=(a00*a28);
  a28=(-a28);
  if (res[1]!=0) res[1][54]=a28;
  a28=(a29*a19);
  a22=(a28+a22);
  a22=(a00*a22);
  a22=(-a22);
  if (res[1]!=0) res[1][55]=a22;
  a19=(a24*a19);
  a31=(a19+a31);
  a31=(a00*a31);
  a31=(-a31);
  if (res[1]!=0) res[1][56]=a31;
  if (res[1]!=0) res[1][57]=a32;
  if (res[1]!=0) res[1][58]=a35;
  if (res[1]!=0) res[1][59]=a34;
  a34=(a29/a21);
  a34=(a02*a34);
  a35=(a20*a34);
  a36=(a35+a36);
  a36=(a00*a36);
  a36=(-a36);
  if (res[1]!=0) res[1][60]=a36;
  a36=(a29*a34);
  a36=(a36+a25);
  a33=(a36+a33);
  a33=(a00*a33);
  a33=(-a33);
  if (res[1]!=0) res[1][61]=a33;
  a34=(a24*a34);
  a37=(a34+a37);
  a37=(a00*a37);
  a37=(-a37);
  if (res[1]!=0) res[1][62]=a37;
  if (res[1]!=0) res[1][63]=a12;
  if (res[1]!=0) res[1][64]=a27;
  if (res[1]!=0) res[1][65]=a26;
  a21=(a24/a21);
  a02=(a02*a21);
  a20=(a20*a02);
  a03=(a20+a03);
  a03=(a00*a03);
  a03=(-a03);
  if (res[1]!=0) res[1][66]=a03;
  a29=(a29*a02);
  a07=(a29+a07);
  a07=(a00*a07);
  a07=(-a07);
  if (res[1]!=0) res[1][67]=a07;
  a24=(a24*a02);
  a24=(a24+a25);
  a10=(a24+a10);
  a10=(a00*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][68]=a10;
  if (res[1]!=0) res[1][69]=a01;
  if (res[1]!=0) res[1][70]=a01;
  if (res[1]!=0) res[1][71]=a01;
  a15=(a00*a15);
  if (res[1]!=0) res[1][72]=a15;
  a28=(a00*a28);
  if (res[1]!=0) res[1][73]=a28;
  a19=(a00*a19);
  if (res[1]!=0) res[1][74]=a19;
  a35=(a00*a35);
  if (res[1]!=0) res[1][75]=a35;
  a36=(a00*a36);
  if (res[1]!=0) res[1][76]=a36;
  a34=(a00*a34);
  if (res[1]!=0) res[1][77]=a34;
  a20=(a00*a20);
  if (res[1]!=0) res[1][78]=a20;
  a29=(a00*a29);
  if (res[1]!=0) res[1][79]=a29;
  a00=(a00*a24);
  if (res[1]!=0) res[1][80]=a00;
  if (res[1]!=0) res[1][81]=a01;
  if (res[1]!=0) res[1][82]=a01;
  if (res[1]!=0) res[1][83]=a01;
  a00=-1.;
  if (res[2]!=0) res[2][0]=a00;
  if (res[2]!=0) res[2][1]=a00;
  if (res[2]!=0) res[2][2]=a00;
  if (res[2]!=0) res[2][3]=a00;
  if (res[2]!=0) res[2][4]=a00;
  if (res[2]!=0) res[2][5]=a00;
  if (res[2]!=0) res[2][6]=a00;
  if (res[2]!=0) res[2][7]=a00;
  if (res[2]!=0) res[2][8]=a00;
  if (res[2]!=0) res[2][9]=a00;
  if (res[2]!=0) res[2][10]=a00;
  if (res[2]!=0) res[2][11]=a00;
  if (res[2]!=0) res[2][12]=a00;
  if (res[2]!=0) res[2][13]=a00;
  if (res[2]!=0) res[2][14]=a00;
  if (res[2]!=0) res[2][15]=a00;
  if (res[2]!=0) res[2][16]=a00;
  if (res[2]!=0) res[2][17]=a00;
  if (res[2]!=0) res[2][18]=a00;
  if (res[2]!=0) res[2][19]=a00;
  if (res[2]!=0) res[2][20]=a00;
  if (res[2]!=0) res[2][21]=a00;
  if (res[2]!=0) res[2][22]=a00;
  if (res[2]!=0) res[2][23]=a00;
  if (res[3]!=0) res[3][0]=a01;
  if (res[3]!=0) res[3][1]=a01;
  if (res[3]!=0) res[3][2]=a01;
  return 0;
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void masses_chain_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void masses_chain_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void masses_chain_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void masses_chain_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int masses_chain_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int masses_chain_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real masses_chain_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* masses_chain_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* masses_chain_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* masses_chain_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* masses_chain_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int masses_chain_impl_dae_fun_jac_x_xdot_u_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
