// ocp/integrators/rk_explicit.hpp
//
// Allocation-free explicit Runge-Kutta integrator (phases 4b, 4g, 4h, 4i).
//
// ExplicitRkIntegrator turns a (possibly time-varying) ODE
//  xdot = f(x, u, t)  into the discrete dynamics
//  x_next = Phi(x, u, t_k)  via a fixed explicit RK scheme
// (ButcherTableau<Dims, NS, Tag>). It implements the ODE-derivative contract
// (value / jacobian / hess_prod, see ode_model.hpp) plus the fused triplet
// entries value_jac / value_jac_hess_prod, so it can be wrapped by
// ContinuousProblem into an ocp::Problem. Nothing downstream of the problem
// interface (QP, SQP, ...) changes.
//
// Multi-step (phase 4g): the OCP interval of size h is subdivided into
// NumSteps sub-intervals of size h_ss = h/NumSteps. `value` chains the
// single-step RK sweep over the sub-steps; `jacobian` threads the
// first-order sensitivity forward across sub-steps; `hess_prod` (non-AD
// path) runs one continuous backward adjoint sweep across all sub-steps.
// NumSteps = 1 (the default) is the plain single-step integrator and is
// bit-for-bit identical to 4b.
//
// Time-varying (phase 4h): each method receives `t_k` (the start of the OCP
// interval). The per-stage physical time is
//     t_s = t_k + h_ss * (ss + c[s])
// and is forwarded to every ODE evaluation (f, jacobian, hess_prod).
//
// Automatic differentiation (phase 4i): when the ODE model's `f` is a
// template method in the scalar type (as generated by AutoDiffOde), the
// composed map's value and all its derivatives are obtained by evaluating
// the RK stage recursion itself in dual scalars:
//
//   - value / jacobian / value_jac: one forward pass in
//     dual<scalar_t, nIn> (one pass per RHS evaluation, i.e. NS * NumSteps
//     total; the value and all nIn first-order partials come out of the
//     same pass);
//   - hess_prod / value_jac_hess_prod: one forward pass in the nested
//     dual<dual<scalar_t, nIn>, 1> type (inner multidual = full gradient
//     basis, outer single dual = the HVP direction v); the multiplier w is
//     contracted only at extraction, after the single pass. No adjoint
//     sweep, and no per-output HVP loop.
//
//   For hand-written ODE models (f evaluated only at scalar_t) the legacy
//   paths are used: analytic/threaded Jacobians and the explicit-dual
//   reverse-mode adjoint sweep for HVPs. The AD path is selected at compile
//   time by ode_f_evaluable_at (the ODE's f must be callable with the dual
//   scalar type and return Matrix<D, nx, 1>).
//
// Forward cache: the v-independent forward state of the hand-written-ODE
// paths (stage states, stage derivatives K, raw stage Jacobians in the
// workspace) is keyed on (x, u, t_k). A second call with the same key
// (e.g. the nx+nu unit-vector HVPs of
// ContinuousProblem::dynamics_value_jac_hess) reuses it instead of
// re-running the forward. The cache is per-integrator-instance
// (thread-safe by virtue of the per-SQP-worker instances).
//
// Allocation-free: every scratch buffer is a fixed-size std::array of
// compile-time Eigen objects, sized once on NS, NumSteps and Dims::nx/nu
// and reused across calls. The methods are const; the ODE model is held by
// const reference; the per-call scratch is `mutable`.
//
// value() recomputes the stage states from (x, u, t_k) on each call (no
// cached value is assumed), matching how the SQP invokes dynamics_* on its
// own.

#pragma once

#include <array>
#include <type_traits>
#include <utility>

#include "ocp/integrators/butcher.hpp"
#include "ocp/integrators/ode_model.hpp"
#include "ocp/integrators/duals_eigen3.hpp"

namespace ocp
{

namespace detail
{
template <class P, int NS, int NumSteps>
struct ErkWorkspace
{
    using state_t   = typename P::state_t;
    using control_t = typename P::control_t;
    using df_dx_t   = typename P::dyn_df_dx_t;
    using df_du_t   = typename P::dyn_df_du_t;

    using State2 = std::array<std::array<state_t, NS>, NumSteps>;
    using Dfdx2  = std::array<std::array<df_dx_t, NS>, NumSteps>;
    using Dfdu2  = std::array<std::array<df_du_t, NS>, NumSteps>;

    State2 K{};          // stage derivatives K_s (forward)
    State2 x_stage{};    // stage states x_s (forward + backward)
    Dfdx2  JX{};         // df/dx at stage s (forward + backward)
    Dfdu2  JU{};         // df/du at stage s (forward + backward)
    State2 dx{};         // first-order JVP of the stage state
    State2 dK{};         // first-order JVP of K_s (forward)

    // Backward HVP duals (explicit-dual reverse mode, phase 4g)
    State2 ddK_dual{};        // dual on the JVP node dK[ss][s]
    State2 dKval_dual{};      // dual on the value node K[ss][s]
    std::array<state_t, NumSteps + 1> dv_ss{};  // dual on v_ss (JVP boundary)
    std::array<state_t, NumSteps + 1> dx_ss{};  // dual on x_ss (value boundary)
    control_t du{};           // dual on the control u

    // Forward cache for the hand-written-ODE paths: the v-independent
    // forward state above (x_stage, K, JX, JU) is valid for the (x, u, t_k)
    // recorded here.
    state_t   last_x{};
    control_t last_u{};
    double    last_t = 0.0;
    bool      fwd_valid = false;
};

}  // namespace detail

/// Explicit Runge-Kutta integrator for a (time-varying) ODE.
///
/// `NS` is the number of RK stages (1..4 for the explicit tags). `Tag`
/// selects the Butcher scheme (K1Tag..K4Tag). `NumSteps` (phase 4g) is the
/// number of sub-intervals one OCP step of size `h` is divided into; the
/// default of 1 is the plain single-step scheme. The ODE model must provide
/// `f` and (unless it is AD-capable, i.e. `f` is a template method in the
/// scalar type) `jacobian`; a nonlinear ODE must additionally provide
/// `hess_prod` for the non-AD `hess_prod` path and is enforced by
/// `ode_supports_hess_prod` at the `hess_prod` call site.
template <class Dims, class Ode, int NS, class Tag, int NumSteps = 1>
class ExplicitRkIntegrator
{
    using P   = ocp::Problem<Dims>;
    using Tab = ocp::ButcherTableau<Dims, NS, Tag>;

    static constexpr int nx  = P::nx;
    static constexpr int nu  = P::nu;
    static constexpr int nIn = nx + nu;

    using scalar_t = typename P::scalar_t;
    using Dual1    = duals::dual<scalar_t, nIn>;
    using Dual2    = duals::dual<Dual1, 1>;

public:
    using state_t   = typename P::state_t;
    using control_t = typename P::control_t;
    using df_dx_t   = typename P::dyn_df_dx_t;
    using df_du_t   = typename P::dyn_df_du_t;

    /// True when the composed map's value + Jacobian + HVP can be produced
    /// by a single forward pass in a nested dual scalar (i.e. the ODE's `f`
    /// is scalar-templated, as for an AutoDiffOde). Lets
    /// ContinuousProblem dispatch its fused problem entries to one pass
    /// instead of 1 + nIn separate HVP calls.
    static constexpr bool supports_value_jac_hess_prod =
        ode_f_evaluable_at<Ode, Dims, Dual2>;

    /// @param ode the ODE model (held by const reference; must outlive this).
    /// @param h fixed step size for the full OCP interval (h/NumSteps per
    ///          sub-step).
    explicit ExplicitRkIntegrator(const Ode& ode, double h)
        : ode_(ode), h_(h), h_ss_(h / (double)NumSteps)
    {
    }

    /// Discrete map  x_next = Phi(x, u, t_k)  for the full OCP interval of
    /// size h, advanced in NumSteps sub-steps of size h/NumSteps.
    /// `t_k` is the physical time at the start of the OCP interval.
    void value(const state_t& x, const control_t& u, double t_k,
               state_t& x_next) const
    {
        state_t x_cur = x;
        for (int ss = 0; ss < NumSteps; ++ss)
        {
            const double t_0 = t_k + ss * h_ss_;
            ws_.K[ss][0] = ode_.f(x_cur, u, t_0 + h_ss_ * Tab::c[0]);
            for (int s = 1; s < NS; ++s)
            {
                state_t xs = x_cur;
                for (int j = 0; j < s; ++j)
                {
                    if (Tab::A[s][j] != 0.0)
                    {
                        xs += h_ss_ * Tab::A[s][j] * ws_.K[ss][j];
                    }
                }
                ws_.K[ss][s] = ode_.f(xs, u, t_0 + h_ss_ * Tab::c[s]);
            }
            for (int s = 0; s < NS; ++s)
            {
                if (Tab::b[s] != 0.0)
                {
                    x_cur += h_ss_ * Tab::b[s] * ws_.K[ss][s];
                }
            }
        }
        x_next = x_cur;
    }

    /// x_next and the Jacobian  (df_dx, df_du)  of the composed map
    ///  x_next = Phi(x, u, t_k)  in one call.
    ///
    /// For an AD-capable ODE this is a single forward pass in
    /// dual<scalar_t, nIn> (the value and all nIn partials come out of the
    /// same pass); for a hand-written ODE it is the threaded-Jacobian
    /// forward, which additionally populates the hess_prod forward cache.
    void value_jac(const state_t& x, const control_t& u, double t_k,
                   state_t& x_next, df_dx_t& df_dx, df_du_t& df_du) const
    {
        if constexpr (ode_f_evaluable_at<Ode, Dims, Dual1>)
        {
            Eigen::Matrix<Dual1, nx, 1> xd;
            Eigen::Matrix<Dual1, nu, 1> ud;
            seedDual1(x, u, xd, ud);
            Eigen::Matrix<Dual1, nx, 1> out;
            ad_forward(xd, ud, t_k, out);
            extract_jac(out, x_next, df_dx, df_du);
        }
        else
        {
            forward_jac(x, u, t_k, df_dx, df_du, x_next);
        }
    }

    /// Jacobian  (df_dx, df_du)  of the composed map  x_next = Phi(x, u, t_k),
    /// computed by threading the first-order sensitivity forward across the
    /// sub-steps: start Sx = I, Su = 0; per sub-step form the per-sub-step
    /// Jacobian (Jx_ss, Ju_ss) and update Sx = Jx_ss*Sx, Su = Jx_ss*Su + Ju_ss.
    /// (Same path as `value_jac`; x_next is discarded.)
    void jacobian(const state_t& x, const control_t& u, double t_k,
                  df_dx_t& df_dx, df_du_t& df_du) const
    {
        state_t x_next;
        value_jac(x, u, t_k, x_next, df_dx, df_du);
    }

    /// x_next, the Jacobian (df_dx, df_du) and the multiplier-contracted
    /// Hessian-vector product (hv_x, hv_u) of the composed map in one call.
    /// For an AD-capable ODE this is a single nested-dual forward pass (the
    /// value, Jacobian and the HVP all come out of the same pass, with `w`
    /// contracted only at extraction); otherwise it is value_jac + hess_prod.
    void value_jac_hess_prod(const state_t& x, const control_t& u, double t_k,
                             state_t& x_next, df_dx_t& df_dx, df_du_t& df_du,
                             const state_t& w, const state_t& v_x,
                             const control_t& v_u, state_t& hv_x,
                             control_t& hv_u) const
    {
        if constexpr (ode_f_evaluable_at<Ode, Dims, Dual2>)
        {
            Eigen::Matrix<Dual2, nx, 1> xd;
            Eigen::Matrix<Dual2, nu, 1> ud;
            seedDual2(x, u, v_x, v_u, xd, ud);
            Eigen::Matrix<Dual2, nx, 1> out;
            ad_forward(xd, ud, t_k, out);
            extract_hvp(out, w, x_next, df_dx, df_du, hv_x, hv_u);
        }
        else
        {
            value_jac(x, u, t_k, x_next, df_dx, df_du);
            hess_prod(x, u, t_k, w, v_x, v_u, hv_x, hv_u);
        }
    }

    /// Bilinear Hessian-vector product of the composed map, output-contracted
    /// with `w` (state; e.g. the dynamics multiplier) and input direction
    /// `v = (v_x, v_u)`; returns (hv_x, hv_u).
    ///
    /// For an AD-capable ODE: a single forward pass in
    /// dual<dual<scalar_t, nIn>, 1>; the multiplier `w` is contracted only
    /// at extraction.
    ///
    /// For a hand-written nonlinear ODE: one forward pass (reused from the
    /// cache when a prior call used the same (x, u, t_k)) stores the
    /// per-sub-step stage values, Jacobians and first-order JVP; then an
    /// explicit-dual reverse-mode sweep propagates duals over every node of
    /// the JVP + value computation graph. The ODE's `hess_prod` is called
    /// once per stage to inject the second-derivative terms.
    /// Only valid for a nonlinear ODE (the ODE must provide `hess_prod`,
    /// unless the ODE is AD-capable, in which case this path is taken
    /// instead).
    void hess_prod(const state_t& x, const control_t& u, double t_k,
                   const state_t& w, const state_t& v_x, const control_t& v_u,
                   state_t& hv_x, control_t& hv_u) const
    {
        if constexpr (ode_f_evaluable_at<Ode, Dims, Dual2>)
        {
            state_t   x_next;
            df_dx_t   df_dx;
            df_du_t   df_du;
            Eigen::Matrix<Dual2, nx, 1> xd;
            Eigen::Matrix<Dual2, nu, 1> ud;
            seedDual2(x, u, v_x, v_u, xd, ud);
            Eigen::Matrix<Dual2, nx, 1> out;
            ad_forward(xd, ud, t_k, out);
            extract_hvp(out, w, x_next, df_dx, df_du, hv_x, hv_u);
        }
        else if constexpr (ode_supports_hess_prod<Ode, Dims>)
        {
            // v-independent forward (stage states, K, raw stage Jacobians),
            // reused when a prior call used the same (x, u, t_k).
            state_t x_next;
            df_dx_t df_dx;
            df_du_t df_du;
            if (!fwd_hit(x, u, t_k))
            {
                forward_jac(x, u, t_k, df_dx, df_du, x_next);
            }
            thread_jvp(v_x, v_u);
            backward_sweep(t_k, u, w, v_u, hv_x, hv_u);
        }
        else
        {
            static_assert(!ode_f_evaluable_at<Ode, Dims, Dual2>,
                "unreachable: AD path handled above");
            static_assert(ode_supports_hess_prod<Ode, Dims>,
                "ExplicitRkIntegrator::hess_prod: the ODE must provide a "
                "'hess_prod' method (nonlinear ODE). A linear ODE has a zero "
                "Hessian and should not reach this path.");
            hv_x.setZero();
            hv_u.setZero();
        }
    }

private:
    // ---- forward cache (hand-written-ODE paths only) ----

    /// True when the cached v-independent forward state was produced for
    /// exactly this (x, u, t_k) (bit-identical inputs).
    bool fwd_hit(const state_t& x, const control_t& u, double t_k) const
    {
        return ws_.fwd_valid
            && ws_.last_t == t_k
            && (x - ws_.last_x).squaredNorm() == 0.0
            && (u - ws_.last_u).squaredNorm() == 0.0;
    }

    /// v-independent forward for hand-written ODEs: the stage states, stage
    /// derivatives K and the *raw* stage Jacobians (JX, JU) in the workspace
    /// (the layout the JVP threading and the backward sweep expect), plus
    /// the composed-map Jacobian (df_dx, df_du) via local per-sub-step
    /// composition and x_next. Sets the forward cache.
    void forward_jac(const state_t& x, const control_t& u, double t_k,
                     df_dx_t& df_dx, df_du_t& df_du,
                     state_t& x_next) const
    {
        state_t x_cur = x;
        df_dx_t Sx = df_dx_t::Identity();
        df_du_t Su;
        Su.setZero();
        for (int ss = 0; ss < NumSteps; ++ss)
        {
            const double t_0 = t_k + ss * h_ss_;
            ws_.x_stage[ss][0] = x_cur;
            ws_.K[ss][0] = ode_.f(x_cur, u, t_0 + h_ss_ * Tab::c[0]);
            for (int s = 1; s < NS; ++s)
            {
                state_t xs = x_cur;
                for (int j = 0; j < s; ++j)
                {
                    if (Tab::A[s][j] != 0.0)
                    {
                        xs += h_ss_ * Tab::A[s][j] * ws_.K[ss][j];
                    }
                }
                ws_.x_stage[ss][s] = xs;
                ws_.K[ss][s] = ode_.f(xs, u, t_0 + h_ss_ * Tab::c[s]);
            }
            // Raw stage Jacobians (for JVP threading / backward sweep) ...
            for (int s = 0; s < NS; ++s)
            {
                ode_.jacobian(ws_.x_stage[ss][s], u, t_0 + h_ss_ * Tab::c[s],
                              ws_.JX[ss][s], ws_.JU[ss][s]);
            }
            // ... composed locally into the per-sub-step Jacobian.
            df_dx_t Jx_ss = df_dx_t::Identity();
            df_du_t Ju_ss;
            Ju_ss.setZero();
            for (int s = 0; s < NS; ++s)
            {
                df_dx_t Dxs = df_dx_t::Identity();
                df_du_t Dus;
                Dus.setZero();
                for (int j = 0; j < s; ++j)
                {
                    if (Tab::A[s][j] != 0.0)
                    {
                        Dxs += h_ss_ * Tab::A[s][j] * ws_.JX[ss][j];
                        Dus += h_ss_ * Tab::A[s][j] * ws_.JU[ss][j];
                    }
                }
                if (Tab::b[s] != 0.0)
                {
                    Jx_ss += h_ss_ * Tab::b[s] * (ws_.JX[ss][s] * Dxs);
                    Ju_ss += h_ss_ * Tab::b[s] * (ws_.JX[ss][s] * Dus + ws_.JU[ss][s]);
                    x_cur += h_ss_ * Tab::b[s] * ws_.K[ss][s];
                }
            }
            Sx = Jx_ss * Sx;
            Su = Jx_ss * Su + Ju_ss;
        }
        df_dx = Sx;
        df_du = Su;
        x_next = x_cur;
        ws_.last_x = x;
        ws_.last_u = u;
        ws_.last_t = t_k;
        ws_.fwd_valid = true;
    }

    /// Threads the first-order JVP along v = (v_x, v_u) through the cached
    /// forward state (raw stage Jacobians in the workspace), filling dx/dK.
    void thread_jvp(const state_t& v_x, const control_t& v_u) const
    {
        state_t v_ss = v_x;
        for (int ss = 0; ss < NumSteps; ++ss)
        {
            ws_.dx[ss][0] = v_ss;
            ws_.dK[ss][0] = ws_.JX[ss][0] * v_ss + ws_.JU[ss][0] * v_u;
            for (int s = 1; s < NS; ++s)
            {
                state_t dxs = v_ss;
                for (int j = 0; j < s; ++j)
                {
                    if (Tab::A[s][j] != 0.0)
                    {
                        dxs += h_ss_ * Tab::A[s][j] * ws_.dK[ss][j];
                    }
                }
                ws_.dx[ss][s] = dxs;
                ws_.dK[ss][s] = ws_.JX[ss][s] * dxs + ws_.JU[ss][s] * v_u;
            }
            for (int s = 0; s < NS; ++s)
            {
                if (Tab::b[s] != 0.0)
                {
                    v_ss += h_ss_ * Tab::b[s] * ws_.dK[ss][s];
                }
            }
        }
    }

    /// Explicit-dual reverse-mode sweep over the cached forward state;
    /// requires thread_jvp to have run for the same (x, u, t_k).
    ///
    /// The scalar
    ///   s = w^T * v_next   (v_next = DPhi * v)
    /// is differentiated w.r.t. (x, u); the gradient is the HVP
    /// (hv_x, hv_u). Duals are carried on every node (value and JVP).
    ///
    /// Seed:  dual[v_NumSteps] = w;  all other duals = 0.
    /// Answer: hv_x = dual[x_0] = dx_ss[0],  hv_u = du.
    void backward_sweep(double t_k, const control_t& u, const state_t& w,
                        const control_t& v_u, state_t& hv_x,
                        control_t& hv_u) const
    {
        for (int ss = 0; ss < NumSteps; ++ss)
        {
            for (int s = 0; s < NS; ++s)
            {
                ws_.ddK_dual[ss][s].setZero();
                ws_.dKval_dual[ss][s].setZero();
            }
            ws_.dv_ss[ss].setZero();
            ws_.dx_ss[ss].setZero();
        }
        ws_.dv_ss[NumSteps] = w;
        ws_.dx_ss[NumSteps].setZero();
        ws_.du.setZero();

        for (int ss = NumSteps - 1; ss >= 0; --ss)
        {
            const double t_0 = t_k + ss * h_ss_;
            const state_t& dv_next = ws_.dv_ss[ss + 1];
            const state_t& dx_next = ws_.dx_ss[ss + 1];

            // b-update: v_{ss+1} = v_ss + h_ss * sum b_s dK_s
            //           x_{ss+1} = x_ss + h_ss * sum b_s K_s
            ws_.dv_ss[ss] += dv_next;
            ws_.dx_ss[ss] += dx_next;
            for (int s = 0; s < NS; ++s)
            {
                if (Tab::b[s] != 0.0)
                {
                    ws_.ddK_dual[ss][s] += (h_ss_ * Tab::b[s]) * dv_next;
                    ws_.dKval_dual[ss][s] += (h_ss_ * Tab::b[s]) * dx_next;
                }
            }

            for (int s = NS - 1; s >= 0; --s)
            {
                // (1) K_s = f(x_s, u):  dual[K] -> dual[x_s], dual[u]
                state_t dx_stage_local =
                    ws_.JX[ss][s].transpose() * ws_.dKval_dual[ss][s];

                // (2) Hessian: JX/JU depend on (x_s, u); inject ODE HVP.
                state_t hx;
                control_t hu;
                ode_hess_prod<Ode, Dims>(ode_, ws_.x_stage[ss][s], u,
                                         t_0 + h_ss_ * Tab::c[s],
                                         ws_.ddK_dual[ss][s], ws_.dx[ss][s],
                                         v_u, hx, hu);
                dx_stage_local += hx;
                const control_t du_stage =
                    ws_.JU[ss][s].transpose() * ws_.dKval_dual[ss][s] + hu;
                ws_.du += du_stage;

                // (3) x_s = x_ss + h_ss sum_{j<s} A[s][j] K_j:
                //     dual[x_s] -> dual[x_ss], dual[K_j]
                ws_.dx_ss[ss] += dx_stage_local;
                for (int j = 0; j < s; ++j)
                {
                    if (Tab::A[s][j] != 0.0)
                    {
                        ws_.dKval_dual[ss][j] +=
                            h_ss_ * Tab::A[s][j] * dx_stage_local;
                    }
                }

                // (4) dK_s = JX_s dx_s + JU_s v_u:  dual[dK] -> dual[dx_s]
                const state_t ddx_local =
                    ws_.JX[ss][s].transpose() * ws_.ddK_dual[ss][s];

                // (5) dx_s = v_ss + h_ss sum_{j<s} A[s][j] dK_j:
                //     dual[dx_s] -> dual[v_ss], dual[dK_j]
                ws_.dv_ss[ss] += ddx_local;
                for (int j = 0; j < s; ++j)
                {
                    if (Tab::A[s][j] != 0.0)
                    {
                        ws_.ddK_dual[ss][j] +=
                            h_ss_ * Tab::A[s][j] * ddx_local;
                    }
                }
            }
        }
        hv_x = ws_.dx_ss[0];
        hv_u = ws_.du;
    }

    // ---- AD front paths (scalar-templated ODE f, phase 4i) ----

    /// Seed the (x, u) input for the Dual1 pass: input k carries the unit
    /// vector e_k in its nIn-partial storage (z = [x; u]).
    void seedDual1(const state_t& x, const control_t& u,
                   Eigen::Matrix<Dual1, nx, 1>& xd,
                   Eigen::Matrix<Dual1, nu, 1>& ud) const
    {
        for (int k = 0; k < nx; ++k)
        {
            xd(k) = Dual1::variable(x(k), k);
        }
        for (int k = 0; k < nu; ++k)
        {
            ud(k) = Dual1::variable(u(k), nx + k);
        }
    }

    /// Seed the (x, u) input for the Dual2 pass: inner multidual rpart =
    /// z_k with partials e_k (the full nIn gradient basis); outer single
    /// dual rpart = v_k with zero partials (the HVP direction).
    void seedDual2(const state_t& x, const control_t& u,
                   const state_t& v_x, const control_t& v_u,
                   Eigen::Matrix<Dual2, nx, 1>& xd,
                   Eigen::Matrix<Dual2, nu, 1>& ud) const
    {
        for (int k = 0; k < nx; ++k)
        {
            xd(k) = Dual2(Dual1::variable(x(k), k), Dual1(v_x(k)));
        }
        for (int k = 0; k < nu; ++k)
        {
            ud(k) = Dual2(Dual1::variable(u(k), nx + k), Dual1(v_u(k)));
        }
    }

    /// The RK stage recursion evaluated in scalar type D (one pass over all
    /// sub-steps; NS * NumSteps evaluations of ode_.f in D).
    template <class D>
    void ad_forward(const Eigen::Matrix<D, nx, 1>& x0,
                    const Eigen::Matrix<D, nu, 1>& u_d, double t_k,
                    Eigen::Matrix<D, nx, 1>& x_next) const
    {
        Eigen::Matrix<D, nx, 1> x_cur = x0;
        for (int ss = 0; ss < NumSteps; ++ss)
        {
            const double t_0 = t_k + ss * h_ss_;
            Eigen::Matrix<D, nx, 1> K[NS];
            K[0] = ode_.f(x_cur, u_d, t_0 + h_ss_ * Tab::c[0]);
            for (int s = 1; s < NS; ++s)
            {
                Eigen::Matrix<D, nx, 1> xs = x_cur;
                for (int j = 0; j < s; ++j)
                {
                    if (Tab::A[s][j] != 0.0)
                    {
                        xs += h_ss_ * Tab::A[s][j] * K[j];
                    }
                }
                K[s] = ode_.f(xs, u_d, t_0 + h_ss_ * Tab::c[s]);
            }
            for (int s = 0; s < NS; ++s)
            {
                if (Tab::b[s] != 0.0)
                {
                    x_cur += h_ss_ * Tab::b[s] * K[s];
                }
            }
        }
        x_next = x_cur;
    }

    /// Value + Jacobian from the final Dual1 state: the value is the real
    /// part; partial k (z = [x; u]) is column k of the composed Jacobian.
    void extract_jac(const Eigen::Matrix<Dual1, nx, 1>& out,
                     state_t& x_next, df_dx_t& df_dx,
                     df_du_t& df_du) const
    {
        for (int i = 0; i < nx; ++i)
        {
            x_next(i) = out(i).rpart();
            for (int j = 0; j < nx; ++j)
            {
                df_dx(i, j) = out(i).dpart(j);
            }
            for (int j = 0; j < nu; ++j)
            {
                df_du(i, j) = out(i).dpart(nx + j);
            }
        }
    }

    /// Value + Jacobian + HVP from the final Dual2 state. The HVP
    /// (hv_x, hv_u) of the composed map along v = (v_x, v_u) contracted
    /// with `w`: r(j) = out(i).dpart(0).dpart(j) is the j-th partial of the
    /// linear form  g = w^T * out,  so  (hv_x, hv_u) = sum_i w_i * r_i.
    void extract_hvp(const Eigen::Matrix<Dual2, nx, 1>& out,
                     const state_t& w, state_t& x_next, df_dx_t& df_dx,
                     df_du_t& df_du, state_t& hv_x, control_t& hv_u) const
    {
        for (int i = 0; i < nx; ++i)
        {
            x_next(i) = out(i).rpart().rpart();
            for (int j = 0; j < nx; ++j)
            {
                df_dx(i, j) = out(i).rpart().dpart(j);
            }
            for (int j = 0; j < nu; ++j)
            {
                df_du(i, j) = out(i).rpart().dpart(nx + j);
            }
        }
        hv_x.setZero();
        hv_u.setZero();
        for (int i = 0; i < nx; ++i)
        {
            const scalar_t wi = w(i);
            if (wi == 0.0)
            {
                continue;
            }
            for (int j = 0; j < nx; ++j)
            {
                hv_x(j) += wi * out(i).dpart(0).dpart(j);
            }
            for (int j = 0; j < nu; ++j)
            {
                hv_u(j) += wi * out(i).dpart(0).dpart(nx + j);
            }
        }
    }

    const Ode& ode_;
    double h_;
    double h_ss_;
    mutable detail::ErkWorkspace<P, NS, NumSteps> ws_;
};

}  // namespace ocp
